[versions]
androidLint = "31.13.0"
android-gradle = "8.13.0"
androidx-activityKtx="1.11.0"
androidx-annotation = "1.9.1"
androidx-constraintlayout="2.2.1"
androidx-datastore = "1.1.7"
androidx-navigation = "2.9.5"
androidx-preference = "1.2.1"
androidx-room = "2.8.2"
cameraVersion = "1.5.2"
dokka = "2.0.0"
hiltAndroid = "2.56.2"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"
lottie = "6.6.2"
mlKitBarcodeScanningCommon = "17.0.0"
mlKitBarcodeScanning = "18.3.1"
moshi = "1.15.2"
retrofit2 = "3.0.0"
rikka-refine = "4.4.0"
sesl-core = "1.17.0+1.0.7-sesl8+rev1"
sesl-coreKtx = "1.17.0+1.0.0-sesl8+rev0"
sesl-appcompat = "1.7.1+1.0.21-sesl8+rev6"
sesl-indexscroll = "1.0.0+1.0.0-sesl8+rev0"
sesl-pickerColor = "1.0.2+1.0.3-sesl8+rev0"
sesl-pickerBasic = "1.0.7+1.0.7-sesl8+rev2"
sesl-pickerApp = "1.0.6+1.0.6-sesl8+rev0"
sesl-preference = "1.2.1+1.0.0-sesl8+rev1"
sesl-material = "1.12.0+1.0.32-sesl8+rev1"
sesl-drawerlayout = "1.2.0+1.0.0-sesl8+rev0"
sesl-customview = "1.2.0-rc01+1.0.0-sesl8+rev0"
sesl-slidingpanelayout = "1.2.0+1.0.4-sesl8+rev0"
sesl-recyclerview = "1.4.0+1.0.12-sesl8+rev2"
sesl-fragment = "1.8.9+1.0.5-sesl8+rev1"
sesl-coordinator = "1.3.0+1.0.0-sesl8+rev0"
sesl-swiperefreshlayout = "1.2.0-alpha01+1.0.0-sesl8+rev0"
sesl-viewpager2 = "1.1.0+1.0.0-sesl8+rev0"

zxing-core = "3.5.3"


[libraries]
androidLintApi = { module = "com.android.tools.lint:lint-api", version.ref = "androidLint" }
androidx-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activityKtx" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraVersion" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraVersion" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraVersion" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraVersion" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-datastoreCore = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-navigation-fragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-runtimeKtx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "androidx-navigation" }
androidx-navigation-uiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidx-preference" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

glide = { module = "com.github.bumptech.glide:glide", version = "5.0.5" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

mlkit-barcodeScanningCommon = { module = "com.google.mlkit:barcode-scanning-common", version.ref = "mlKitBarcodeScanningCommon" }
mlkit-barcodeScanning = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "mlKitBarcodeScanning" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

oneuiDesign = { module = "io.github.tribalfs:oneui-design", version = "0.8.13+oneui8" }
oneuiIcons = { module = "io.github.oneuiproject:icons", version = "1.1.0" }

retrofit2 = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
rikka-refineRuntime = { module = "dev.rikka.tools.refine:runtime", version.ref = "rikka-refine" }
rikka-refineAnnotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "rikka-refine" }
rikka-refineAnnotationProcessor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "rikka-refine" }

sesl-appcompat = { module = "sesl.androidx.appcompat:appcompat", version.ref = "sesl-appcompat" }
sesl-core = { module = "sesl.androidx.core:core", version.ref = "sesl-core" }
sesl-coreKtx = { module = "sesl.androidx.core:core-ktx", version.ref = "sesl-coreKtx" }
sesl-indexscroll = { module = "sesl.androidx.indexscroll:indexscroll", version.ref = "sesl-indexscroll" }
sesl-pickerColor = { module = "sesl.androidx.picker:picker-color", version.ref = "sesl-pickerColor" }
sesl-pickerBasic = { module = "sesl.androidx.picker:picker-basic", version.ref = "sesl-pickerBasic" }
sesl-pickerApp = { module = "sesl.androidx.picker:picker-app", version.ref = "sesl-pickerApp" }
sesl-preference = { module = "sesl.androidx.preference:preference", version.ref = "sesl-preference" }
sesl-material = { module = "sesl.com.google.android.material:material", version.ref = "sesl-material" }
sesl-drawerlayout = { module = "sesl.androidx.drawerlayout:drawerlayout", version.ref = "sesl-drawerlayout" }
sesl-customview = { module = "sesl.androidx.customview:customview", version.ref = "sesl-customview" }
sesl-slidingpanelayout = { module = "sesl.androidx.slidingpanelayout:slidingpanelayout", version.ref = "sesl-slidingpanelayout" }
sesl-recyclerview = { module = "sesl.androidx.recyclerview:recyclerview", version.ref = "sesl-recyclerview" }
sesl-coordinatorlayout = { module = "sesl.androidx.coordinatorlayout:coordinatorlayout", version.ref = "sesl-coordinator" }
sesl-swiperefreshlayout = { module = "sesl.androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "sesl-swiperefreshlayout" }
sesl-fragment = { module = "sesl.androidx.fragment:fragment", version.ref = "sesl-fragment" }
sesl-viewpager2 = { module = "sesl.androidx.viewpager2:viewpager2", version.ref = "sesl-viewpager2" }

zxing-core = { module = "com.google.zxing:core", version.ref = "zxing-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"}
dokka-javadoc = { id = "org.jetbrains.dokka-javadoc", version.ref = "dokka"}
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
maven-publish = { id = "maven-publish"}
rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "rikka-refine" }

[bundles]
androidx-camera = ["androidx-camera-camera2", "androidx-camera-core", "androidx-camera-lifecycle", "androidx-camera-view"]
androidx-datastore = ["androidx-datastoreCore", "androidx-datastorePreferences"]
androidx-navigation = ["androidx-navigation-runtimeKtx", "androidx-navigation-fragmentKtx", "androidx-navigation-uiKtx"]
androidx-room = ["androidx-room-ktx", "androidx-room-compiler"]
hilt = ["hilt-android"]
hilt-compilers = ["hilt-android-compiler"]
mlkitBarcodeScanning = ["mlkit-barcodeScanning", "mlkit-barcodeScanningCommon"]
moshi = ["moshi", "moshi-kotlin"]
retrofit2 = ["retrofit2", "retrofit2-converter-gson"]
sesl-androidx = ["sesl-appcompat",
    "sesl-coordinatorlayout",
    "sesl-recyclerview",
    "sesl-customview",
    "sesl-drawerlayout",
    "sesl-slidingpanelayout",
    "sesl-indexscroll",
    "sesl-pickerBasic",
    "sesl-pickerColor",
    "sesl-preference",
    "sesl-swiperefreshlayout",
    "sesl-core",
    "sesl-coreKtx",
    "sesl-fragment",
    "sesl-pickerApp",
    "sesl-viewpager2"]